{
 "title": "New dashboard",
 "time": { "from": "2020-02-01T23:00:00.000Z", "to": "2020-09-02T21:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "country",
    "query": "SELECT DISTINCT nomPays FROM pays ORDER BY nomPays;\n"
   }
  ]
 },
 "panels": [
  {
   "title": "CasActifs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  date AS \"time\", \n  casactifs\nFROM \n  statistiques_quotidiennes\nWHERE \n  idpays IN (SELECT idPays FROM pays WHERE nomPays IN ($country))  -- Utilisation correcte de la variable dans Grafana\nORDER BY time;\n"
    }
   ]
  },
  {
   "title": "Guérissons",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \n  date AS \"time\", \n  totalrecuperes\nFROM \n  statistiques_quotidiennes\nWHERE \n  idpays IN (SELECT idPays FROM pays WHERE nomPays IN ($country))  -- Utilisation correcte de la variable dans Grafana\nORDER BY time;\n"
    }
   ]
  },
  {
   "title": "Cas Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \n  date AS \"time\", \n  totalcas\nFROM \n  statistiques_quotidiennes\nWHERE \n  idpays IN (SELECT idPays FROM pays WHERE nomPays IN ($country))  -- Utilisation correcte de la variable dans Grafana\nORDER BY time;\n"
    }
   ]
  },
  {
   "title": "Deces Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  totaldeces\nFROM statistiques_quotidiennes\nWHERE idpays IN (SELECT idPays FROM pays WHERE nomPays IN ($country))  -- Utilisation de `IN` pour plusieurs pays\nORDER BY time;\n"
    }
   ]
  }
 ]
}